# Site settings
title: Alex's Blog
email: weixiang.chen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Record my learning process!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chenweixiang.github.io" # the base hostname & protocol for your site
twitter_username: Weixiang_Chen
github_username: chenweixiang

# Build settings
markdown: kramdown

# Highlight by Pygments
highlighter: true
