# Site settings
title: ALEX's BLOG
email: weixiang.chen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Record my learning process!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chenweixiang.github.io" # the base hostname & protocol for your site
twitter_username: Weixiang_Chen
github_username: chenweixiang

# Include Gems
gems: [jekyll-paginate]

# Build settings
markdown: redcarpet

# Highlight by Pygments
highlighter: pygments

# Post excerpts
excerpt_separator: <!--more-->

# Enable Pagination: Items should be displayed per page
paginate: 20
paginate_path: "page:num"

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: "Chen Weixiang"

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: [with_toc_data]

kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
